// src/app/calculators/utils/exportUtils.ts
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatPercentage } from './formatters';

export const generatePDF = (calculatorId: string, inputs: any, results: any, calculatorName: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(0, 102, 204);
  doc.text(calculatorName, pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, pageWidth / 2, 30, { align: 'center' });
  
  // Summary Section
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', 14, 45);
  
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  
  let yPos = 55;
  
  if (results.summary) {
    doc.text(results.summary, 14, yPos);
    yPos += 10;
  }
  
  // Key Metrics Table
  if (results.metrics && Array.isArray(results.metrics)) {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Metrics', 14, yPos);
    yPos += 10;
    
    const metricsData = results.metrics.map((metric: any) => [
      metric.label,
      metric.value + (metric.unit || '')
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: metricsData,
      theme: 'grid',
      headStyles: { fillColor: [0, 102, 204], textColor: 255 },
      styles: { fontSize: 11, cellPadding: 5 },
      margin: { left: 14, right: 14 }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  // Inputs Breakdown
  if (inputs && Object.keys(inputs).length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Input Parameters', 14, yPos);
    yPos += 10;
    
    const inputsData = Object.entries(inputs).map(([key, value]) => {
      const label = key
        .replace(/([A-Z])/g, ' $1')
        .replace(/^./, str => str.toUpperCase())
        .replace(/([a-z])([A-Z])/g, '$1 $2');
      
      let formattedValue = '';
      if (typeof value === 'string') {
        formattedValue = value;
      } else if (typeof value === 'number') {
        formattedValue = value.toLocaleString();
      } else {
        formattedValue = String(value);
      }
      
      return [label, formattedValue];
    });
    
    autoTable(doc, {
      startY: yPos,
      head: [['Parameter', 'Value']],
      body: inputsData,
      theme: 'grid',
      headStyles: { fillColor: [60, 60, 60], textColor: 255 },
      styles: { fontSize: 10, cellPadding: 4 },
      margin: { left: 14, right: 14 }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  // Footer
  const footerY = pageHeight - 20;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Development Pro Calculators', pageWidth / 2, footerY, { align: 'center' });
  doc.text('https://developmentpro.com.au/calculators', pageWidth / 2, footerY + 6, { align: 'center' });
  
  // Save PDF
  const fileName = `${calculatorName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

export const generateCSV = (inputs: any, results: any, calculatorName: string) => {
  const csvData = [];
  
  // Header
  csvData.push([calculatorName]);
  csvData.push(['Generated on:', new Date().toLocaleString()]);
  csvData.push([]);
  
  // Summary
  if (results.summary) {
    csvData.push(['Summary', results.summary]);
    csvData.push([]);
  }
  
  // Metrics
  if (results.metrics && Array.isArray(results.metrics)) {
    csvData.push(['Key Metrics']);
    results.metrics.forEach((metric: any) => {
      csvData.push([metric.label, metric.value + (metric.unit || '')]);
    });
    csvData.push([]);
  }
  
  // Inputs
  if (inputs && Object.keys(inputs).length > 0) {
    csvData.push(['Input Parameters']);
    Object.entries(inputs).forEach(([key, value]) => {
      const label = key
        .replace(/([A-Z])/g, ' $1')
        .replace(/^./, str => str.toUpperCase())
        .replace(/([a-z])([A-Z])/g, '$1 $2');
      csvData.push([label, String(value)]);
    });
  }
  
  return csvData;
};

export const clearSavedCalculations = () => {
  localStorage.removeItem('savedCalculations');
};

export const getSavedCalculations = () => {
  const saved = localStorage.getItem('savedCalculations');
  return saved ? JSON.parse(saved) : [];
};

export const formatFilename = (calculatorName: string) => {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').split('.')[0];
  return `${calculatorName.replace(/\s+/g, '_')}_${timestamp}`;
};
